name: First Workflow
on: [push]

jobs:
  run-shell-commands:
  #The type of runner that the job will run on
    runs-on: ubuntu-latest
    #Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline Command
        run: |
          node -v
          npm -v